# 02 - Data Cleaning and Transformation Pipeline

**Project:** Uber Data Visualization and Analysis  
**Stage:** Step 2 - Cleaning and Feature Engineering  
**Input:** `data/raw/uber_raw_dataset.csv`  
**Output:** `data/processed/uber_cleaned_dataset.csv`

This notebook applies the production cleaning pipeline and exports the analysis-ready dataset.

In [1]:
from pathlib import Path
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from IPython.display import Markdown, display

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')
sns.set_theme(style='whitegrid', context='notebook')
plt.rcParams['figure.dpi'] = 120
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'data').exists() and (candidate / 'notebooks').exists():
            return candidate
    raise FileNotFoundError('Project root not found from current working directory.')

PROJECT_ROOT = find_project_root(Path.cwd().resolve())


import sys

sys.path.append(str(PROJECT_ROOT))

from scripts.etl_pipeline import (
    engineer_features,
    fix_dtypes,
    load_raw_data,
    remove_anomalies,
    save_processed,
    standardize_text,
    validate,
)

RAW_PATH = PROJECT_ROOT / 'data' / 'raw' / 'uber_raw_dataset.csv'
PROCESSED_PATH = PROJECT_ROOT / 'data' / 'processed' / 'uber_cleaned_dataset.csv'

print(f'Raw file       : {RAW_PATH}')
print(f'Processed file : {PROCESSED_PATH}')

Raw file       : /Users/ravleensingh/Documents/Capstone/DVA_Capstone/Uber_Analysis/data/raw/uber_raw_dataset.csv
Processed file : /Users/ravleensingh/Documents/Capstone/DVA_Capstone/Uber_Analysis/data/processed/uber_cleaned_dataset.csv

## Load and Baseline Checks

In [2]:
df_raw = load_raw_data(RAW_PATH)
display(df_raw.head())

baseline = pd.DataFrame({
    'metric': ['Rows', 'Columns', 'Missing values', 'Duplicate rows', 'Duplicate trip_id'],
    'value': [
        len(df_raw),
        df_raw.shape[1],
        int(df_raw.isna().sum().sum()),
        int(df_raw.duplicated().sum()),
        int(df_raw['trip_id'].duplicated().sum()),
    ],
})
display(baseline)

[LOAD] Loaded 50,000 rows and 14 columns from uber_raw_dataset.csv

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time
0,1,8270,10683,San Francisco,37.17,-77.59,37.17,-77.62,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000
1,2,1860,44743,Boston,38.90,-108.58,38.94,-108.56,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000
2,3,6390,75839,San Francisco,38.81,-89.94,38.82,-89.90,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000
3,4,6191,22189,New York,37.30,-75.33,37.30,-75.32,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000
4,5,6734,61104,Seattle,38.97,-121.48,38.99,-121.47,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000

              metric  value
0               Rows  50000
1            Columns     14
2     Missing values      0
3     Duplicate rows      0
4  Duplicate trip_id      0

## Fix Data Types and Standardize Text

In [3]:
df_step1 = fix_dtypes(df_raw)
df_step2 = standardize_text(df_step1)

dtype_review = pd.DataFrame({
    'column': df_step2.columns,
    'dtype_after_cleaning_step': df_step2.dtypes.astype(str).values,
})
display(dtype_review.head(14))

for col in ['city', 'status', 'payment_method']:
    print()
    print(col.upper())
    print(df_step2[col].value_counts().sort_index().to_string())

[DTYPE] Converted datetime and category columns.
[TEXT] Standardized text columns: stripped whitespace, applied title case.

            column dtype_after_cleaning_step
0          trip_id                     int64
1        driver_id                     int64
2         rider_id                     int64
3             city                  category
4       pickup_lat                   float64
5       pickup_lng                   float64
6         drop_lat                   float64
7         drop_lng                   float64
8      distance_km                   float64
9      fare_amount                   float64
10          status                  category
11  payment_method                  category
12     pickup_time            datetime64[us]
13       drop_time            datetime64[ns]

CITY
city
Boston           8454
Chicago          8345
Los Angeles      8315
New York         8247
San Francisco    8401
Seattle          8238

STATUS
status
Cancelled     4984
Completed    42540
No-Show       2476

PAYMENT_METHOD
payment_method
Card      12533
Cash      12413
UPI       12549
Wallet    12505

## Engineer Analytical Features

In [4]:
df_step3 = engineer_features(df_step2)

derived_cols = [
    'trip_duration_mins', 'pickup_date', 'pickup_hour', 'pickup_day',
    'pickup_month', 'pickup_week', 'time_of_day', 'fare_per_km', 'is_weekend'
]
display(df_step3[derived_cols].head())

[FEATURE] Added 9 derived columns.

,trip_duration_mins,pickup_date,pickup_hour,pickup_day,pickup_month,pickup_week,time_of_day,fare_per_km,is_weekend
0,8.92,2023-01-01,0,Sunday,January,52,Night (0-6),3.61,True
1,25.28,2023-01-01,0,Sunday,January,52,Night (0-6),2.66,True
2,16.38,2023-01-01,0,Sunday,January,52,Night (0-6),2.36,True
3,19.83,2023-01-01,0,Sunday,January,52,Night (0-6),2.38,True
4,31.50,2023-01-01,0,Sunday,January,52,Night (0-6),1.82,True

## Review and Remove Anomalies

In [5]:
anomaly_mask = (df_step3['distance_km'] == 0) & (df_step3['trip_duration_mins'] == 0)
anomalies = df_step3.loc[anomaly_mask, ['trip_id', 'city', 'distance_km', 'fare_amount', 'status', 'pickup_time', 'drop_time', 'trip_duration_mins']]
print(f'Ghost trips identified : {len(anomalies)}')
display(anomalies)

df_clean = remove_anomalies(df_step3)
validate(df_clean)

Ghost trips identified : 3

,trip_id,city,distance_km,fare_amount,status,pickup_time,drop_time,trip_duration_mins
39361,39362,Seattle,0.00,3.97,No-Show,2023-01-28 08:01:00,2023-01-28 08:01:00,0.00
39374,39375,Chicago,0.00,4.02,Completed,2023-01-28 08:14:00,2023-01-28 08:14:00,0.00
44302,44303,Seattle,0.00,2.01,Completed,2023-01-31 18:22:00,2023-01-31 18:22:00,0.00

[ANOMALY] Removed 3 ghost trip(s) (zero distance + zero duration).

============================================================
  VALIDATION REPORT
============================================================
  Null values remaining               : PASS
  Duplicate rows                      : PASS
  Negative fare amounts               : PASS
  Negative distances                  : PASS
  Negative durations                  : PASS
  Drop time before pickup             : PASS
============================================================
  All checks passed.

## Final Cleaned Dataset Review

In [6]:
summary = pd.DataFrame({
    'metric': [
        'Rows after cleaning',
        'Columns after cleaning',
        'Unique cities',
        'Status categories',
        'Pickup date start',
        'Pickup date end',
        'Average trip duration (mins)',
        'Average fare amount',
    ],
    'value': [
        len(df_clean),
        df_clean.shape[1],
        df_clean['city'].nunique(),
        ', '.join(df_clean['status'].astype(str).sort_values().unique()),
        df_clean['pickup_time'].min(),
        df_clean['pickup_time'].max(),
        round(df_clean['trip_duration_mins'].mean(), 2),
        round(df_clean['fare_amount'].mean(), 2),
    ],
})
display(summary)
display(df_clean.head())

                         metric                          value
0           Rows after cleaning                          49997
1        Columns after cleaning                             23
2                 Unique cities                              6
3             Status categories  Cancelled, Completed, No-Show
4             Pickup date start            2023-01-01 00:00:00
5               Pickup date end            2023-02-04 17:19:00
6  Average trip duration (mins)                          21.03
7           Average fare amount                          15.98

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,trip_duration_mins,pickup_date,pickup_hour,pickup_day,pickup_month,pickup_week,time_of_day,fare_per_km,is_weekend
0,1,8270,10683,San Francisco,37.17,-77.59,37.17,-77.62,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:55,8.92,2023-01-01,0,Sunday,January,52,Night (0-6),3.61,True
1,2,1860,44743,Boston,38.90,-108.58,38.94,-108.56,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17,25.28,2023-01-01,0,Sunday,January,52,Night (0-6),2.66,True
2,3,6390,75839,San Francisco,38.81,-89.94,38.82,-89.90,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:23,16.38,2023-01-01,0,Sunday,January,52,Night (0-6),2.36,True
3,4,6191,22189,New York,37.30,-75.33,37.30,-75.32,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:50,19.83,2023-01-01,0,Sunday,January,52,Night (0-6),2.38,True
4,5,6734,61104,Seattle,38.97,-121.48,38.99,-121.47,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30,31.50,2023-01-01,0,Sunday,January,52,Night (0-6),1.82,True

## Export Cleaned Dataset

In [7]:
save_processed(df_clean, PROCESSED_PATH)
print(f'Exists after export: {PROCESSED_PATH.exists()}')

[SAVE] Exported 49,997 rows and 23 columns to /Users/ravleensingh/Documents/Capstone/DVA_Capstone/Uber_Analysis/data/processed/uber_cleaned_dataset.csv
Exists after export: True